### ISSUE TITLE
What does the "Single parameter required" error mean?

### ISSUE THREAD

**Issue by ShinyJustyZ** [SmylerMC/smybteapi#5]
I'm trying to get the zoom levels for custom terraplusplus terrain, but after self-hosting via docker and running the command 
`curl 127.0.0.1:8080/webmercator/resolution?latitude=54`
I get the error: `{"error":"Single parameter required","details":"The \u0027latitude\u0027 is needed exactly once."}`
What does it mean and how can I fix it? Is it an error on the code or my request command?

**Comment by SmylerMC** [comment]
This error is supposed to tell you that you provided an argument multiple times when it is expected only once. It was obviously a bug, which is now fixed (along with an improved error message).

Example URL: https://smybteapi.smyler.net/webmercator/resolution?latitude=54

Thanks for reporting.
